./Make.sh FinalSelectionOriginal.cc
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/Data.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/Data.root data_obs data_obs iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYSall.root DYS120 DYS iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYBall.root DYB DYB iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYJall.root DYJ DYJ iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY1.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYS1.root DYS120 DYS iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY1.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYB1.root DYB DYB iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY1.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYJ1.root DYJ DYJ iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY2.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYS2.root DYS120 DYS iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY2.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYB2.root DYB DYB iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY2.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYJ2.root DYJ DYJ iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY3.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYS3.root DYS120 DYS iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY3.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYB3.root DYB DYB iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY3.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYJ3.root DYJ DYJ iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY4.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYS4.root DYS120 DYS iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY4.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYB4.root DYB DYB iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY4.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYJ4.root DYJ DYJ iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
hadd -f /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYJ.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYJall.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYJ1.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYJ2.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYJ3.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYJ4.root
hadd -f /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYB.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYBall.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYB1.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYB2.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYB3.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYB4.root
hadd -f /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYS.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYSall.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYS1.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYS2.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYS3.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYS4.root
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/TT.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/TT.root TT TT iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/W.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/Wincl.root W W iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/W1.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/W1.root W W iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/W2.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/W2.root W W iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/W3.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/W3.root W W iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/W4.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/W4.root W W iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
hadd -f /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/Wunscaled.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/W4.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/W3.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/W2.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/W1.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/Wincl.root
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/ST_t_antitop.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/ST_t_antitop.root ST_t_antitop VV iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/ST_tW_antitop.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/ST_tW_antitop.root ST_tW_antitop VV iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/ST_t_top.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/ST_t_top.root ST_t_top VV iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/ST_tW_top.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/ST_tW_top.root ST_tW_top VV iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/WW1L1Nu2Q.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/WW1L1Nu2Q.root WW1L1Nu2Q VV iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/VV2L2Nu.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/VV2L2Nu.root VV2L2Nu VV iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
#./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/WZJLLLNu.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/WZLLLNu.root WZLLLNu VV iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/ZZ2L2Q.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/ZZ2L2Q.root ZZ2L2Q VV iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/ZZ4L.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/ZZ4L.root ZZ4L VV iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/WZ2L2Q.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/WZ2L2Q.root WZ2L2Q VV iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/WZ1L3Nu.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/WZ1L3Nu.root WZ1L3Nu VV iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/WZ1L1Nu2Q.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/WZ1L1Nu2Q.root WZ1L1Nu2Q VV iso MVAoldM mvis all old 0 10 20 0 3 0 2000 1 1
hadd -f /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/VV.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/ST_tW_top.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/ST_t_top.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/ST_tW_antitop.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/ST_t_antitop.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/VV2L2Nu.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/WW1L1Nu2Q.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/ZZ2L2Q.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/ZZ4L.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/WZ2L2Q.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/WZ1L3Nu.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/WZ1L1Nu2Q.root



./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYSall.root DYS120 DYS iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYBall.root DYB DYB iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYJall.root DYJ DYJ iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY1.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYS1.root DYS120 DYS iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY1.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYB1.root DYB DYB iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY1.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYJ1.root DYJ DYJ iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY2.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYS2.root DYS120 DYS iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY2.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYB2.root DYB DYB iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY2.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYJ2.root DYJ DYJ iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY3.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYS3.root DYS120 DYS iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY3.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYB3.root DYB DYB iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY3.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYJ3.root DYJ DYJ iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY4.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYS4.root DYS120 DYS iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY4.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYB4.root DYB DYB iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY4.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYJ4.root DYJ DYJ iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
hadd -f /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYJ.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYJall.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYJ1.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYJ2.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYJ3.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYJ4.root
hadd -f /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYS.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYSall.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYS1.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYS2.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYS3.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYS4.root
hadd -f /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYB.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYBall.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYB1.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYB2.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYB3.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYB4.root
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/TT.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/TT.root TT TT iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/W.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/Wincl.root W W iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/W1.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/W1.root W W iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/W2.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/W2.root W W iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/W3.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/W3.root W W iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/W4.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/W4.root W W iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
hadd -f /afs/cern.ch/work/m/mshi/public/files_upinvMass/Wunscaled.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/W4.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/W3.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/W2.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/W1.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/Wincl.root
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/ST_t_antitop.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/ST_t_antitop.root ST_t_antitop VV iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/ST_tW_antitop.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/ST_tW_antitop.root ST_tW_antitop VV iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/ST_t_top.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/ST_t_top.root ST_t_top VV iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/ST_tW_top.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/ST_tW_top.root ST_tW_top VV iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/WW1L1Nu2Q.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/WW1L1Nu2Q.root WW1L1Nu2Q VV iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/VV2L2Nu.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/VV2L2Nu.root VV2L2Nu VV iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
#./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/WZJLLLNu.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/WZLLLNu.root WZLLLNu VV iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/ZZ2L2Q.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/ZZ2L2Q.root ZZ2L2Q VV iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/ZZ4L.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/ZZ4L.root ZZ4L VV iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/WZ2L2Q.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/WZ2L2Q.root WZ2L2Q VV iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/WZ1L3Nu.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/WZ1L3Nu.root WZ1L3Nu VV iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/WZ1L1Nu2Q.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/WZ1L1Nu2Q.root WZ1L1Nu2Q VV iso MVAoldM mvis all old 1 10 20 0 3 0 2000 1 1
hadd -f /afs/cern.ch/work/m/mshi/public/files_upinvMass/VV.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/ST_tW_top.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/ST_t_top.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/ST_tW_antitop.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/ST_t_antitop.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/VV2L2Nu.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/WW1L1Nu2Q.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/ZZ2L2Q.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/ZZ4L.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/WZ2L2Q.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/WZ1L3Nu.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/WZ1L1Nu2Q.root

./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYBall_muD.root DYB DYB iso MVAoldM mvis all old 2 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY1.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYB1_muD.root DYB DYB iso MVAoldM mvis all old 2 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY2.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYB2_muD.root DYB DYB iso MVAoldM mvis all old 2 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY3.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYB3_muD.root DYB DYB iso MVAoldM mvis all old 2 10 20 0 3 0 2000 1 1
./FinalSelectionOriginal.exe /afs/cern.ch/work/m/mshi/public/AnalyzeInput/DY4.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYB4_muD.root DYB DYB iso MVAoldM mvis all old 2 10 20 0 3 0 2000 1 1
hadd -f /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYB_muD.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYBall_muD.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYB1_muD.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYB2_muD.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYB3_muD.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYB4_muD.root


python Scale_WOriginal.py --scale nominal --anti iso
python Create_QCDOriginal.py --scale nominal 
python Create_QCDOriginal.py --scale wup
python Create_QCDOriginal.py --scale wdown
python Create_QCDOriginal.py --scale shapeup
python Create_QCDOriginal.py --scale shapedown
python Scale_processOriginal.py --input /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/W.root --output /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/W_wnorm.root --hist W --postfixP _Wnorm --postfixF _Wnorm --factor 0.10

hadd -f final_nominal.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/W.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/Data.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYS.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYB.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/TT.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/QCD.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/VV.root  /afs/cern.ch/work/m/mshi/public/files_wupinvMass/QCD.root /afs/cern.ch/work/m/mshi/public/files_wdowninvMass/QCD.root /afs/cern.ch/work/m/mshi/public/files_shapeupinvMass/QCD.root /afs/cern.ch/work/m/mshi/public/files_shapedowninvMass/QCD.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/W_wnorm.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYJ.root /afs/cern.ch/work/m/mshi/public/files_nominalinvMass/DYB_muD.root 
hadd -f final_up.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/Wunscaled.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYS.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYB.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/TT.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/VV.root /afs/cern.ch/work/m/mshi/public/files_upinvMass/DYJ.root
hadd -f final.root final_nominal.root final_up.root

cp -f final.root /afs/cern.ch/work/m/mshi/public/files_mvisinvMass/mvis_MVAoldM_testQCDShapeUncertainty_dm-all_dmf-old_eta-0-3_pt-10-20.root

