mkdir -p /afs/cern.ch/work/m/mshi/public/outputTauID/Out_DY1low
mkdir -p /afs/cern.ch/work/m/mshi/public/outputTauID/Out_DY1
mkdir -p /afs/cern.ch/work/m/mshi/public/outputTauID/Out_DY2
mkdir -p /afs/cern.ch/work/m/mshi/public/outputTauID/Out_DY3
mkdir -p /afs/cern.ch/work/m/mshi/public/outputTauID/Out_DY4
mkdir -p /afs/cern.ch/work/m/mshi/public/outputTauID/Out_DYlow
mkdir -p /afs/cern.ch/work/m/mshi/public/outputTauID/Out_DY_v
mkdir -p /afs/cern.ch/work/m/mshi/public/outputTauID/Out_ST_tW_antitop
mkdir -p /afs/cern.ch/work/m/mshi/public/outputTauID/Out_ST_tW_top
mkdir -p /afs/cern.ch/work/m/mshi/public/outputTauID/Out_TT
mkdir -p /afs/cern.ch/work/m/mshi/public/outputTauID/Out_W1
mkdir -p /afs/cern.ch/work/m/mshi/public/outputTauID/Out_W4_v
mkdir -p /afs/cern.ch/work/m/mshi/public/outputTauID/Out_WW1L1Nu2Q
mkdir -p /afs/cern.ch/work/m/mshi/public/outputTauID/Out_WZ1L1Nu2Q
mkdir -p /afs/cern.ch/work/m/mshi/public/outputTauID/Out_WZ1L3Nu
mkdir -p /afs/cern.ch/work/m/mshi/public/outputTauID/Out_WZ2L2Q
mkdir -p /afs/cern.ch/work/m/mshi/public/outputTauID/Out_WZ3LNu
mkdir -p /afs/cern.ch/work/m/mshi/public/outputTauID/Out_ZZ2L2Q
mkdir -p /afs/cern.ch/work/m/mshi/public/outputTauID/Out_ZZ4L
mkdir -p /afs/cern.ch/work/m/mshi/public/outputTauID/Out_ZZ
mkdir -p /afs/cern.ch/work/m/mshi/public/outputTauID/Out_DY2low
mkdir -p /afs/cern.ch/work/m/mshi/public/outputTauID/Out_W2_v
mkdir -p /afs/cern.ch/work/m/mshi/public/outputTauID/Out_W3_v
mkdir -p /afs/cern.ch/work/m/mshi/public/outputTauID/Out_W_v
mkdir -p /afs/cern.ch/work/m/mshi/public/outputTauID/Out_WWLNuQQ
mkdir -p /afs/cern.ch/work/m/mshi/public/outputTauID/Out_ST_t_top
mkdir -p /afs/cern.ch/work/m/mshi/public/outputTauID/Out_VV2L2Nu
